---
- name: General configuration
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest
      tags: [ update, upgrade ]
        
    - name: Install python pip
      apt:
        name: python3-pip
        state: latest
      tags: [ update, upgrade, docker ]

  roles:
    - role: users_mgmt
      tags: users
    - role: firewall
      tags: firewall
    - role: docker_config
      tags: docker
    - role: reboot_check
      tags: always

- name: Swarm manager configuration
  hosts: swarm_manager
  gather_facts: false

  roles:
    - role: docker_swarm_manager_init
      tags: swarm

- name: Swarm nodes configuration
  hosts: swarm_nodes
  gather_facts: false

  roles:
    - role: docker_swarm_nodes
      tags: swarm

- name: Prepare nodes to deploy Cassandra
  hosts: all
  gather_facts: false

  tasks:
    - name: Make sure that destination dir exists.
      file:
        path: "/opt/cassandra/data"
        state: directory
        recurse: yes
      tags: cassandra

- name: Deploy Cassandra
  hosts: swarm_manager
  gather_facts: false

  roles:
    - role: cassandra
      tags: cassandra
