---
- name: General configuration
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest
      tags: [ update, upgrade ]
        
    - name: Install python pip
      apt:
        name: python3-pip
        state: latest
      tags: [ update, upgrade, docker ]

  roles:
    - role: firewall
      tags: firewall
    - role: docker_config
      tags: docker
    - role: reboot_check
      tags: always

- name: Swarm manager configuration
  hosts: swarm_manager
  gather_facts: true

  roles:
    - role: docker_swarm_manager_init
      tags: swarm


- name: Swarm nodes configuration
  hosts: swarm_nodes
  gather_facts: true

  roles:
    - role: docker_swarm_nodes
      tags: swarm
