---
  all:
    vars:
      ansible_port: 22
      ansible_user: root
      ansible_become: yes
      ansible_ssh_private_key_file: /Users/dyego.eugenio/.ssh/dyego/id_rsa
      ansible_python_interpreter: auto_silent
    children:
      swarm_manager:
        hosts:
          ubuntu-s-1vcpu-2gb-fra1-01:
            ansible_host: "164.90.183.169"
      swarm_nodes:
        hosts:
          ubuntu-s-1vcpu-2gb-fra1-02:
            ansible_host: "161.35.206.33"
          ubuntu-s-1vcpu-2gb-fra1-03:
            ansible_host: "46.101.239.88"
